#!/usr/bin/env node
// Layer 3 (execution): one token source → three platform artifacts.
// Reads 02-design-system/tokens/tokens.seed.json and emits:
//   1. 04-prototyping/app/src/design-system/generated/tokens.css  (CSS custom properties + platform override blocks)
//   2. 02-design-system/dist/Tokens.swift                          (SwiftUI color/metric constants)
//   3. 02-design-system/dist/tokens.xml                            (Android resources)
// Deterministic, idempotent, no interactive input. Run: node scripts/generate-tokens.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const seed = JSON.parse(readFileSync(join(root, '02-design-system/tokens/tokens.seed.json'), 'utf8'));
const { primitive, semantic, platforms } = seed;

// ---- ref resolution: "{blue.500}" → primitive.color.blue["500"], "{radius.button}" → primitive.radius.button
function resolve(value) {
  if (typeof value !== 'string' || !value.startsWith('{')) return value;
  const path = value.slice(1, -1).split('.');
  const [head, ...rest] = path;
  const groups = [primitive.color, primitive, semantic];
  for (const g of groups) {
    if (g && g[head] !== undefined) {
      let node = g[head];
      for (const k of rest) node = node?.[k];
      if (node !== undefined) return resolve(node);
    }
  }
  throw new Error(`Unresolvable token ref: ${value}`);
}

const kebab = (s) => s.replace(/\./g, '-');

// ---- 1. CSS custom properties
let css = `/* GENERATED by scripts/generate-tokens.mjs from 02-design-system/tokens/tokens.seed.json — do not edit by hand. */\n:root {\n`;

// primitives useful at runtime
for (const [k, v] of Object.entries(primitive.font)) css += `  --font-${k}: ${v};\n`;
for (const [k, v] of Object.entries(primitive.space)) css += `  --space-${k}: ${v};\n`;
for (const [k, v] of Object.entries(primitive.radius)) css += `  --radius-${k}: ${v};\n`;
for (const [k, v] of Object.entries(primitive.size)) css += `  --size-${kebab(k)}: ${v};\n`;
for (const [k, v] of Object.entries(primitive.duration)) css += `  --duration-${k}: ${v};\n`;

// semantic groups → flat vars
for (const [group, tokens] of Object.entries(semantic)) {
  for (const [name, value] of Object.entries(tokens)) {
    if (typeof value === 'object') {
      // composite (type styles)
      for (const [prop, pv] of Object.entries(value)) {
        const out = prop === 'family' ? `var(--font-${pv})` : resolve(String(pv));
        css += `  --${group}-${kebab(name)}-${kebab(prop)}: ${out};\n`;
      }
    } else {
      css += `  --${group}-${kebab(name)}: ${resolve(value)};\n`;
    }
  }
}
css += `}\n\n`;

// platform override blocks — only the divergence set, each with its guideline
const dividerWidth = { hairline: '0.5px', elevation: '0px', border: '1px' };
const motionEase = {
  spring: 'cubic-bezier(0.32, 0.72, 0, 1)',
  'emphasized-easing': 'cubic-bezier(0.2, 0, 0, 1)',
  'ease-out': 'ease-out',
};
for (const [platform, ov] of Object.entries(platforms)) {
  css += `/* ${platform.toUpperCase()} — ${ov.$guideline} */\n[data-platform="${platform}"] {\n`;
  if (ov['control.radius']) css += `  --control-radius: ${resolve(ov['control.radius'])};\n`;
  if (ov['control.height']) css += `  --control-height: ${resolve(ov['control.height'])};\n`;
  if (ov['target-min']) css += `  --target-min: ${ov['target-min']};\n`;
  if (ov.divider) css += `  --divider-width: ${dividerWidth[ov.divider]};\n`;
  if (ov.divider === 'elevation') css += `  --list-shadow: var(--shadow-card); /* M3: tonal elevation instead of dividers */\n`;
  else css += `  --list-shadow: none;\n`;
  if (ov.motion) css += `  --motion-ease: ${motionEase[ov.motion]};\n`;
  if (ov.presentation) css += `  --presentation: ${ov.presentation};\n`;
  if (ov.focus === 'visible-ring') css += `  --focus-ring: 2px solid var(--border-focus); /* web: visible focus rings */\n`;
  else css += `  --focus-ring: none;\n`;
  css += `}\n\n`;
}

const cssOut = join(root, '04-prototyping/app/src/design-system/generated/tokens.css');
mkdirSync(dirname(cssOut), { recursive: true });
writeFileSync(cssOut, css);

// ---- 2. Tokens.swift (semantic colors + metrics)
const swiftColor = (hex) => {
  const h = hex.replace('#', '');
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
  return `Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`;
};
const camel = (s) => s.replace(/[-.](\w)/g, (_, c) => c.toUpperCase());
let swift = `// GENERATED by scripts/generate-tokens.mjs — one source of truth: tokens.seed.json\nimport SwiftUI\n\nenum MBTokens {\n  // MARK: Semantic colors\n`;
for (const [group, tokens] of Object.entries(semantic)) {
  for (const [name, value] of Object.entries(tokens)) {
    if (typeof value === 'object') continue;
    const v = resolve(value);
    if (/^#([0-9A-Fa-f]{6})$/.test(v)) swift += `  static let ${camel(`${group}-${name}`)} = ${swiftColor(v)}\n`;
  }
}
swift += `\n  // MARK: Metrics (HIG platform values apply via ios overrides)\n`;
for (const [k, v] of Object.entries(primitive.radius)) swift += `  static let radius${camel(`-${k}`)}: CGFloat = ${parseFloat(v)}\n`;
for (const [k, v] of Object.entries(primitive.size)) swift += `  static let ${camel(k)}: CGFloat = ${parseFloat(v)}\n`;
swift += `}\n`;
const swiftOut = join(root, '02-design-system/dist/Tokens.swift');
mkdirSync(dirname(swiftOut), { recursive: true });
writeFileSync(swiftOut, swift);

// ---- 3. tokens.xml (Android resources; M3 platform values noted)
const snake = (s) => s.replace(/[-.]/g, '_');
let xml = `<?xml version="1.0" encoding="utf-8"?>\n<!-- GENERATED by scripts/generate-tokens.mjs — one source of truth: tokens.seed.json -->\n<resources>\n`;
for (const [group, tokens] of Object.entries(semantic)) {
  for (const [name, value] of Object.entries(tokens)) {
    if (typeof value === 'object') continue;
    const v = resolve(value);
    if (/^#([0-9A-Fa-f]{6})$/.test(v)) xml += `  <color name="${snake(`${group}_${name}`)}">${v}</color>\n`;
  }
}
for (const [k, v] of Object.entries(primitive.radius)) xml += `  <dimen name="radius_${snake(k)}">${parseFloat(v)}dp</dimen>\n`;
for (const [k, v] of Object.entries(primitive.size)) xml += `  <dimen name="${snake(k)}">${parseFloat(v)}dp</dimen>\n`;
xml += `  <!-- M3 overrides: target-min 48dp, control radius = pill, tonal elevation (see tokens.seed.json platforms.android) -->\n</resources>\n`;
writeFileSync(join(root, '02-design-system/dist/tokens.xml'), xml);

console.log('✓ tokens.css, Tokens.swift, tokens.xml generated from tokens.seed.json');
